In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('../../Computer-Vision-with-Python/Computer-Vision-with-Python/DATA/bank_note_data.txt', delimiter = ',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:, 4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features =  data[:, 0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [11]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [12]:
len(X_train)

919

In [13]:
len(X)

1372

In [14]:
len(X_train) / len(X)

0.6698250728862973

In [15]:
len(X_test) / len(X)

0.3301749271137026

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
scaler_object = MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler()

In [19]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [20]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [21]:
from keras.models import Sequential
from keras.layers import Dense


In [22]:
model = Sequential()
#input layer: 4 dimention for 4 columns
#relu fuction outputs values between 0 - Infinity
model.add(Dense(4, input_dim = 4, activation = 'relu'))
#middle layer: just give the optimal number
model.add(Dense(8, activation = 'relu'))
#output layer: it will have 1 for 1 output
#sigmoid function outputs values between 0 - 1
model.add(Dense(1, activation = 'sigmoid'))

In [24]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [26]:
model.fit(scaled_X_train, y_train, epochs = 50, verbose = 2)

Epoch 1/50
29/29 - 1s - loss: 0.6918 - accuracy: 0.4505 - 1s/epoch - 36ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6880 - accuracy: 0.5321 - 50ms/epoch - 2ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6842 - accuracy: 0.6605 - 59ms/epoch - 2ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6804 - accuracy: 0.7584 - 60ms/epoch - 2ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6768 - accuracy: 0.7573 - 54ms/epoch - 2ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6726 - accuracy: 0.7726 - 49ms/epoch - 2ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6673 - accuracy: 0.7933 - 53ms/epoch - 2ms/step
Epoch 8/50
29/29 - 0s - loss: 0.6612 - accuracy: 0.7965 - 67ms/epoch - 2ms/step
Epoch 9/50
29/29 - 0s - loss: 0.6523 - accuracy: 0.8041 - 59ms/epoch - 2ms/step
Epoch 10/50
29/29 - 0s - loss: 0.6410 - accuracy: 0.8052 - 58ms/epoch - 2ms/step
Epoch 11/50
29/29 - 0s - loss: 0.6283 - accuracy: 0.8096 - 56ms/epoch - 2ms/step
Epoch 12/50
29/29 - 0s - loss: 0.6148 - accuracy: 0.8118 - 57ms/epoch - 2ms/step
Epoch 13/50
29/29 - 0s - loss: 0.6005 

In [28]:
# model.predict_classes(scaled_X_test)

In [29]:
model.metrics_names

['loss', 'accuracy']

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

In [38]:
predictions = model.predict(scaled_X_test)
predictions = np.round(predictions).astype(int)

In [39]:
confusion_matrix(y_test, predictions)

array([[249,   8],
       [ 25, 171]], dtype=int64)

In [41]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.91      0.97      0.94       257
         1.0       0.96      0.87      0.91       196

    accuracy                           0.93       453
   macro avg       0.93      0.92      0.92       453
weighted avg       0.93      0.93      0.93       453



In [42]:
model.save('myFirstModel.h5')

In [43]:
from keras.models import load_model

In [44]:
newModel = load_model('myFirstModel.h5')

In [45]:
np.round((newModel.predict(scaled_X_test)))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],